# Generated by Django 3.2.8 on 2021-12-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='user',
            new_name='follower',
        ),
    ]
