# Generated by Django 3.2.8 on 2021-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/%y/%m'),
        ),
    ]
